"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

import os
from setuptools import setup

SOURCE_PATH = os.path.join(os.getcwd(), 'src')
APP = [os.path.join(SOURCE_PATH, 'ednexport.pyw')]
IMGS_PATH = os.path.join(os.getcwd(), 'imgs')
DATA_FILES = [('imgs', [os.path.join(IMGS_PATH, 'green.png'),
                        os.path.join(IMGS_PATH, 'red.png'),
                        os.path.join(IMGS_PATH, 'yellow.png'),
                        os.path.join(IMGS_PATH, 'info.png'),
                        os.path.join(IMGS_PATH, 'question.png'),
                        os.path.join(IMGS_PATH, 'warning.png'),
                        os.path.join(IMGS_PATH, 'error.png'),
                        os.path.join(IMGS_PATH, 'ednexport.png'),
                        os.path.join(IMGS_PATH, 'ednexport.icns')])]
APP_NAME = "EDNExport"
DESCRIPTION = 'Exportação e atualização dos dados do DNE'
COMPANY_NAME = 'Fausto Ferreira - BaDcereal'
COPYRIGHT = f'Copyright © 2023, {COMPANY_NAME}, MIT License'
OPTIONS = {
    'plist': {
        'CFBundleName': APP_NAME,
        'CFBundleDisplayName': APP_NAME,
        'CFBundleGetInfoString': "EDNE Export Data",
        'CFBundleIdentifier': "com.metaedne.osx.ednexport",
        'CFBundleVersion': "0.0.1",
        'CFBundleShortVersionString': "beta 0.0.1",
        'NSHumanReadableCopyright': COPYRIGHT
    },
    'iconfile': os.path.join(IMGS_PATH, 'ednexport.icns'),
}

setup(
    app=APP,
    name=APP_NAME,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
    license='MIT',  # Adiciona a licença MIT
)
